services:
  jupyter:
    build: .
    container_name: gps_jupyter
    ports:
      - "8888:8888"
      - "4040:4040"
    volumes:
      - .:/workspace
    environment:
      - CONDA_ENV=gps-analytics

  socket:
    build: .
    container_name: socket_stream
    ports:
      - "9999:9999"
    volumes:
      - .:/workspace
    command: conda run --no-capture-output -n gps-analytics python src/socket_mock.py

  postgres:
    image: postgis/postgis:15-3.3
    container_name: gps_postgres
    environment:
      POSTGRES_DB: taxi_db
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: taxi
    ports:
      - "5432:5432"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  grafana:
    image: grafana/grafana:10.4.2
    container_name: gps_grafana
    ports:
      - "3001:3000"
    depends_on:
      - postgres
    volumes:
    - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
    environment:
    - GF_SECURITY_ADMIN_USER=admin
    - GF_SECURITY_ADMIN_PASSWORD=admin
