apiVersion: 1
datasources:
  - name: TaxiDB
    type: postgres
    access: proxy
    url: postgres:5432 
    user: taxi
    secureJsonData:
      password: 'taxi'
    jsonData:
      database: taxi_db
      sslmode: 'disable'
    isDefault: true
